version: '3.1'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: velopolio
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 3307:3306







